Configs: &Default
  Version: 2
  AppName: <%- applicationNameContext %>
  ServerSettings:
    VerifyPhoneCodeLength: 6
    ForceDisableInputSocial: False
  Analytics:
    Google: 
      Enable: <%- enableGoogleAnalytics %>
  CachePolicyEnabled: True
  ResendCodeConfirmTime: 60 #Время ожидания для повторной отправки кода подтверждения (секунды)
  AnonymVirtualCard: True #Виртуальная карта для анонима 
  ShowOptions:
    ProfileCardViewModel: All #Отображать в меню "Моя карта" All or OnlyAuth
    PersonalOffersViewModel: <%- enablePersonalOffers %> #Отображать в меню "Персональные акции" OnlyAuth or Never
    PersonalGoodsViewModel: <%- enablePersonalGoods %> #Отображать в меню "Любимые товары" OnlyAuth or Never
  Localization:
    Enable: False #Подключение локализации
    ViewLocalization: False #Отображение стартового экрана с выбором языка при первом запуске приложения
  PrereviewScreensEnable: True

Development:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: <%- serverUrlContext %>
    AuthorizationUrl: <%- serverAuthorizationUrlContext %>
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp: 
    AppKey:
      Android: False
      Ios: False
    EnableCrashManager: False
  PushNotification: 
    Enable: <%- enablePushNotification %>

Staging:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: <%- serverUrlContext %>
    AuthorizationUrl: <%- serverAuthorizationUrlContext %>
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp:
    AppKey:
      Android: "required"
      Ios: "required"
    EnableCrashManager: True
  PushNotification: 
    Enable: <%- enablePushNotification %>

Production:
  <<: *Default
  LoymaxEndpoint:
    AppUrl: <%- serverUrlContext %>
    AuthorizationUrl: <%- serverAuthorizationUrlContext %>
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp: 
    AppKey:
      Android: "required"
      Ios: "required"
    EnableCrashManager: True
  PushNotification: 
    Enable: <%- enablePushNotification %>