Order:
  - SignInViewModel.Title
  - ProfileCardViewModel.Title
  - OffersViewModel.Title
  - PersonalOffersViewModel.Title
  - PersonalGoods.Title
  - ShoppingBasketsViewModel.Title
  - MerchantsViewModel.Title
  - PurchaseHistoryViewModel.Title
  - NotificationsViewModel.Title
  - ProfileViewModel.Title
  - SupportService.Title 
  - AboutApp.Title